### ISSUE TITLE
Header Templateの作成

### ISSUE THREAD

**Issue by Walkmana-25** [s1f102402091/team-project1#1]
Menu barのテンプレートを作成する。

**Comment by s1f102402091** [comment]
よろしく。
１個目

**Comment by Walkmana-25** [comment]
![image](https://github.com/s1f102402091/team-project1/assets/50088655/97af2cef-02bc-4cc8-aad8-4eccc92746b4)
HeaderのTemplateをこのように作成してみました。

**Comment by Walkmana-25** [comment]
#8
